# This file was generated by GoReleaser. DO NOT EDIT.
cask "fibe" do
  version "0.2.41"

  on_macos do
    on_intel do
      sha256 "7081fbab76b48be7efc1e415910872773faf76b016d0a3e8c66bc1d680108300"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
    on_arm do
      sha256 "572c007986d79d262aa346af059e39351e7ae2c6390524c3d52d0158aa275254"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
  end

  on_linux do
    on_intel do
      sha256 "5c9a4f3382b70d9935fd038c78a33d84905be262c4a063cde6d0297d2d49e1f0"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
    on_arm do
      sha256 "3008e4fa3654165080a3b3a940903d31d5bd736b477ed54a46e340704bbce045"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
  end

  name "fibe"
  desc "Official Go SDK, CLI, and MCP server for the Fibe platform"
  homepage "https://github.com/fibegg/sdk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fibe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fibe"]
    end
  end

  # No zap stanza required

end
