# This file was generated by GoReleaser. DO NOT EDIT.
cask "fibe" do
  version "0.2.45"

  on_macos do
    on_intel do
      sha256 "9fe4d8e6e0b12c04ceee597bb51dbb0b44040625aa195dad0256d034f674591e"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
    on_arm do
      sha256 "a8af19b03f9b38f6dc966c37c8e8146846eea259d7cc37a61ea6be87d69deee0"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
  end

  on_linux do
    on_intel do
      sha256 "e27e6ecd222f29e0733b89f018761bba71d4fd1675c8bd7c3570c6e8c069529d"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
    on_arm do
      sha256 "d1407bfee2ed72dafdaec529cf4c69d0d54684d2a7fa04011205a95a42a3077a"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
  end

  name "fibe"
  desc "Official Go SDK, CLI, and MCP server for the Fibe platform"
  homepage "https://github.com/fibegg/sdk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fibe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fibe"]
    end
  end

  # No zap stanza required

end
