# This file was generated by GoReleaser. DO NOT EDIT.
cask "fibe" do
  version "0.2.42"

  on_macos do
    on_intel do
      sha256 "268e37b74555a91e6ec0c70434aa958525a6d1477f01b97515000bd0df49eaf8"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
    on_arm do
      sha256 "9fbff90fa817cbda27a7dcdd424fc56b772ba7fb1895cbfa03bf281ea65981d8"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
  end

  on_linux do
    on_intel do
      sha256 "45bdcb51e96ccc14705f1c0f076e4e8a166674452d764d51579f884480a6e7be"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_linux_amd64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
    on_arm do
      sha256 "57904b7ce58baaf983869ba9785c09376738e96d697395061dc0edeff4a440cc"
      url "https://github.com/fibegg/sdk/releases/download/v#{version}/fibe_#{version}_linux_arm64.tar.gz",
        verified: "github.com/fibegg/sdk"
    end
  end

  name "fibe"
  desc "Official Go SDK, CLI, and MCP server for the Fibe platform"
  homepage "https://github.com/fibegg/sdk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fibe"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/fibe"]
    end
  end

  # No zap stanza required

end
