# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fibe < Formula
  desc "Official Go SDK, CLI, and MCP server for the Fibe platform"
  homepage "https://github.com/fibegg/sdk"
  version "0.2.20"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.20/fibe_0.2.20_darwin_amd64.tar.gz"
      sha256 "2d853e6700b7ed012949615465e86ea19dadb47460ad1bc5dd3bbbcc5292abcd"

      define_method(:install) do
        bin.install "fibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.20/fibe_0.2.20_darwin_arm64.tar.gz"
      sha256 "0fa1feca792ba079318a7eb5d020ec49b99e9c940db805b6f5a2dcedf04c6763"

      define_method(:install) do
        bin.install "fibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.20/fibe_0.2.20_linux_amd64.tar.gz"
      sha256 "908a6ddd450e2570f2c6a523f5fc8c24fd73f80a549873873d4498cdebf2daf6"
      define_method(:install) do
        bin.install "fibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.20/fibe_0.2.20_linux_arm64.tar.gz"
      sha256 "da97bc2c060bbbf116c3ce130c972857db939eda08444691f03058c1e8b6b2b9"
      define_method(:install) do
        bin.install "fibe"
      end
    end
  end

  test do
    system "#{bin}/fibe", "version"
  end
end
