# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fibe < Formula
  desc "Official Go SDK, CLI, and MCP server for the Fibe platform"
  homepage "https://github.com/fibegg/sdk"
  version "0.2.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.7/fibe_0.2.7_darwin_amd64.tar.gz"
      sha256 "d3fd058eb2a684210f47afb4526d42941f00d84cb619b47488fa07d88811c9c9"

      define_method(:install) do
        bin.install "fibe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.7/fibe_0.2.7_darwin_arm64.tar.gz"
      sha256 "d4def666d90d064aa7cbd5984091c77e68098666833783799ce2f85c3342f526"

      define_method(:install) do
        bin.install "fibe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.7/fibe_0.2.7_linux_amd64.tar.gz"
      sha256 "308c7c7a70b983844a8d371f127c2356e7303b1cbbbbf4f003a335f38cc3e9a6"
      define_method(:install) do
        bin.install "fibe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fibegg/sdk/releases/download/v0.2.7/fibe_0.2.7_linux_arm64.tar.gz"
      sha256 "02ccd349b114fdf8dfc92836edc55cbfeb506a8b72583a3aba32eaa6833ab686"
      define_method(:install) do
        bin.install "fibe"
      end
    end
  end

  test do
    system "#{bin}/fibe", "version"
  end
end
